spring:
  application:
    name: turbine
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
<<<<<<< HEAD
  instance:
    prefer-ip-address: true
         
=======
      
>>>>>>> branch 'master' of https://github.com/WindLee05-17/story.git
turbine:
  app-config: order-service, feign
  cluster-name-expression: new String("default")